development:
  forest_env_secret: 2fa307edb5276bbb93b48c81dcd0ea1cb6a20bf245be0eac7dab332469b88baa
  forest_auth_secret: OALB7X6rw75sc5oDhhDh3w
staging:
  forest_env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
  forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>
production:
  forest_env_secret: 277973c2531b95ddaff2d0f723c448800b3182add835ad774e7ca80c6e6e4d91
  forest_auth_secret: txhnqm0JaPxdmA3pajp2bLbyJDHs8cDy